apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fod8d07ph-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fod8d07ph-go 
  name: fod8d07ph-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fod8d07ph-go 
